FROM kanapi/kanapi-bbs
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
ENV TRAVIS="true"
ENV CI="true"
COPY kanapi /kanapi_build/kanapi
RUN mkdir -p ${HOME}/ci_src; cd /kanapi_build/kanapi/kanapi_system/kanapi-cli; ./install cli
CMD ["/bin/bash"]
