#!/bin/bash

git clone https://github.com/jdanecki/kanapi.git kanapi
if [ "${SHIPPABLE}" = "true" -o  "${TRAVIS}" = "true" ]
then
	docker build -f Dockerfile-travis -t kanapi-cli:ci-base .
else
	docker build -t kanapi-cli:ci-base .
fi

