FROM kanapi/kanapi-bbs
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
ENV TRAVIS="true"
ENV CI="true"
COPY kanapi /kanapi_build/kanapi
RUN mkdir -p ${HOME}/ci_src; /kanapi_build/kanapi/kanapi_system/docker/configure; cd /kanapi_build/kanapi/kanapi_system/x86_64 && ./install cli-base
CMD ["/bin/bash"]
